# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('lorawan-zigbee-example', ['lora-zigbee', 'lorawan', 'lr-wpan'])
    obj.source = 'lora-zigbee-example.cc'

