# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('lora-zigbee', ['core', 'network', 'mobility', 'spectrum', 'propagation', 'applications']) # , 'visualizer'])
    module.source = [
        'model/lora-zigbee-error-model.cc',
        'model/lora-zigbee-interference-helper.cc',
        'model/lora-zigbee-phy.cc',
        'model/lora-zigbee-mac.cc',
        'model/lora-zigbee-mac-header.cc',
        'model/lora-zigbee-mac-trailer.cc',
        'model/lora-zigbee-csmaca.cc',
        'model/lora-zigbee-net-device.cc',
        'model/lora-zigbee-spectrum-value-helper.cc',
        'model/lora-zigbee-spectrum-signal-parameters.cc',
        'model/lora-zigbee-lqi-tag.cc',
        'helper/lora-zigbee-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('lora-zigbee')
    module_test.source = [
        'test/lora-zigbee-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'lora-zigbee'
    headers.source = [
        'model/lora-zigbee-error-model.h',
        'model/lora-zigbee-interference-helper.h',
        'model/lora-zigbee-phy.h',
        'model/lora-zigbee-mac.h',
        'model/lora-zigbee-mac-header.h',
        'model/lora-zigbee-mac-trailer.h',
        'model/lora-zigbee-csmaca.h',
        'model/lora-zigbee-net-device.h',
        'model/lora-zigbee-spectrum-value-helper.h',
        'model/lora-zigbee-spectrum-signal-parameters.h',
        'model/lora-zigbee-lqi-tag.h',
        'helper/lora-zigbee-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

